[package]
name = "russ"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
csv = "1.4.0"
macroquad = "0.4.14"
num-traits = "0.2.19"
plotters = "0.3.7"
rand = "0.9.2"
ratatui = "0.30.0"
